### ISSUE TITLE
Git Live extension causing repeated type and lint checking of closed files.

### ISSUE THREAD

**Issue by copleykj** [GitLiveApp/GitLive#119]
Issue Type: <b>Bug</b>

1. Have a large codebase
2. change types in a file that affects others with your codebase that aren't currently open
3. Observe the "PROBLEMS" tab of the vscode panel to see that different type issues and linting errors of closed files pop in and out of the panel infinitely
4. Observe high CPU load and UI stutter/freeze on

I was having this issue and discovered that if I disabled extensions that it went away. I used extension bisect to narrow it down to this extension.

Extension version: 15.0.6
VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:08:42.978Z)
OS version: Linux x64 5.13.19-2-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|11.52GB (1.83GB free)|
|Process Argv|--unity-launch --crash-reporter-id 12244778-b6a7-4f4b-89d7-fc573259c323|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by Steakeye** [comment]
Hi @copleykj,

Would you mind telling us what kind of size of code base you're working with? That is to say, how many files of source code. If it's an open source project we'd love to investigate with the actual code base, so if it's possible for you to share the repo, that would be great. Not to worry if that's not possible.

A screen shot of your problems tab might prove insightful if you could share that with us; either on this thread or emailing support@git.live.

Additionally, would you be able to give an estimate of what kind of impact your refactoring is having on your codebase? For example, we tried to replicate your problem but using one of our own internal projects, with a test refactor that impacted under 20 files; this had negligible affect on CPU bandwidth. So in order to try to create a test more comparable to your own situation, it would be really useful to get an idea of how many files are automatically refactored, when you're updating types in another file, specifically in the case that has caused your problem.

Thanks,
Andrew

**Comment by Steakeye** [comment]
Hi @copleykj,

Happy Friday! Just wondering if you'd be able to provide the extra information I asked for to better help us solve the issue you're experiencing?

Have a good weekend 😄

**Comment by copleykj** [comment]
Sorry for the delay. So I've tried to re-enable to extension to get screen shots of the problems tab and now the issue seems to have resolved itself, so I'm not sure something was cached or what's going on, but I'm gonna close this for now and I'll reopen with more details if it starts happening again.

**Comment by Steakeye** [comment]
Thanks for the update @copleykj. Please don’t hesitate to let us know if the problem reoccurs.
