### ISSUE TITLE
IDE Fatal Error when trying to run the plugin

### ISSUE THREAD

**Issue by pillscapsules** [GitLiveApp/GitLive#48]
A couple of days ago I removed my account from the Gitlive plugin, and now I can't run it; I've tried uninstalling and reinstalling multiple times, tried checking the plugin settings page, still doesn't work. The error that is displayed is attached below.
[stacktrace.txt](https://github.com/GitLiveApp/GitLive/files/6281337/stacktrace.txt)
![idefatalerror](https://user-images.githubusercontent.com/73193114/114094022-cd76f980-9889-11eb-9c9c-9445819f5ad1.png)

![image](https://user-images.githubusercontent.com/73193114/114094118-ee3f4f00-9889-11eb-9b5e-c847079ba70a.png)
Nothing is displayed when I try to go into the settings page for the plugin.

**Comment by nbransby** [comment]
This has been fixed in the next version but to avoid having to wait for it to be released you can do the following:
- Exit the IDE
- Open the other.xml from the options dierctory specifed in https://www.jetbrains.com/help/idea/tuning-the-ide.html#config-directory
- Remove the property with the name `app.teamhub.com.google.firebase.auth.FIREBASE_USER`
- Start the IDE

**Comment by pillscapsules** [comment]
That worked, thank you!
